### ISSUE TITLE
CI processes in v2: add daily builds

### ISSUE THREAD

**Issue by vuilleumierc** [openoereb/pyramid_oereb#1321]
Add the following in GitHub actions:

- [x] Publish the app documentation on `gh-pages` (relevant when https://github.com/openoereb/pyramid_oereb/issues/1257 is done) -> there is now a dedicated ticket for that, #1410 

- [ ] Daily deploy to PyPi

- [x] Add unit tests and optionally integration tests (when tests are fixed, see issues with label `Broken test`, other related issues: https://github.com/openoereb/pyramid_oereb/issues/1300 and https://github.com/openoereb/pyramid_oereb/issues/1174) -> there are now dedicated tickets for that, #1390 and the following

- [x] Publish Docker image (optionally) -> there is now a dedicated ticket for that, #1332
